### ISSUE TITLE
regarding setCursor, chooseAction and performAction functions

### ISSUE THREAD

**Issue by S1LV3RJ1NX** [shivamkajale/Manimouse#1]
I want to know how did you find out the conditions for mouse actions like if <40 then right click and so on.
Also in performAction i did not understand complete if-else ladder How did you arrive at those coordinates. Will you plz help me in understanding those? Great project!!

**Comment by udion** [comment]
It's mostly an observation which seemed to work, maybe you can find a better value :)

**Comment by S1LV3RJ1NX** [comment]
how did you do that observation how can i do the same?

**Comment by udion** [comment]
The outer 'if' you see checks when to register the action and when not to hence 'perform',
The numbers such as 110,120,390,590 define the boundary of the screen on which we want to be active flawlessly, those numbers are found by trials and estimated so that it performs well on 15.6 inch laptop with standard resolution. (why not whole screen you question? because at the boundaries it's very hard to control the movements of the cursor. If you run the code you will see it happening, to over come the problem once the cursor goes out of the bounding box we define, we place the cursor at fixed co-ordinates using the numbers such as 1912,1072,8, which is again what we found to be working well on standard 1920X1080 taking into account the padding of 8 pixels).

Some constants which you see like 
```
cursor[0] = 4*(yp[0]-110)
cursor[1] = 4*(yp[1]-120)
``` 
we multiply the actual co-ordinates by a scaling factor (4, again a general observation) because moving a cursor just by a pixel would make it move too slow.

rest of the if else ladder is  self explanatory I guess. Feel free to shoot, if not.

**Comment by S1LV3RJ1NX** [comment]
Tysm. I am recreating your project after learning openCv to be honest your
project was the reason for me to start learning openCv and python.
